name: Lint CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  check-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Check Solidity Style
        run: forge fmt --check
